# Generated by Django 4.0.1 on 2022-01-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountmodel_options_accountmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='date',
        ),
    ]
