# Generated by Django 4.0.1 on 2022-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accountmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
