# Generated by Django 4.0.1 on 2022-01-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='date',
        ),
    ]
