# Generated by Django 4.0.1 on 2022-01-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_accountmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'ordering': ('-created',), 'verbose_name': 'Account'},
        ),
    ]
