# Generated by Django 4.0.1 on 2022-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_alter_demands_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demands',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
